#!/bin/bash

if type -p java;
then
    _java=java
else
    _java="$JAVA_HOME/bin/java" 2> /dev/null
fi

if [[ ! $@ =~ ^\-.+ ]];
then
  echo "Usage:"
      echo "    adrenalina -s    Adrenalina server."
      echo "    adrenalina -c    Adrenalina console client."
      echo "    adrenalina -g    Adrenalina GUI client."
      exit 0
fi

while getopts ":scg" opt; do
  case ${opt} in
    s )
      $_java -jar jar/server-jar-with-dependencies.jar
      ;;
    c )
      $_java -jar jar/client-jar-with-dependencies.jar c
      ;;
    g )
      $_java -jar jar/client-jar-with-dependencies.jar
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))
