#!/bin/bash

if type -p java;
then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];
then
    _java="$JAVA_HOME/bin/java" 2> /dev/null
else
    echo "Java not found."
fi

if [[ ! $@ =~ ^\-.+ ]]
then
  echo "Usage:"
      echo "    adrenalina -s    Adrenalina server."
      echo "    adrenalina -c    Adrenalina console client."
      echo "    adrenalina -g    Adrenalina GUI client."
      exit 0
fi

while getopts ":scg" opt; do
  case ${opt} in
    s )
      $_java -jar out/artifacts/Server/AM48.jar
      ;;
    c )
      $_java -jar out/artifacts/Client/AM48.jar c
      ;;
    g )
      $_java -jar out/artifacts/Client/AM48.jar g
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))
